export * from './is';
export * from './is-array';
export * from './is-big-int';
export * from './is-boolean';
export * from './is-date';
export * from './is-defined';
export * from './is-error';
export * from './is-function';
export * from './is-null';
export * from './is-number';
export * from './is-object';
export * from './is-object-tag';
export * from './is-plain-object';
export * from './is-reg-exp';
export * from './is-string';
export * from './is-symbol';
export * from './is-undefined';
export * from './is-void';

